CREATE DATABASE IF NOT EXISTS mi_database;
USE mi_database;

CREATE TABLE IF NOT EXISTS datos (
  id INT,
  nombre STRING,
  valor DOUBLE
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS TEXTFILE;

LOAD DATA LOCAL INPATH '/data/datos.csv' INTO TABLE datos;
